---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-12.04
  run_list:
  - "recipe[apt]"
  driver:
    image: ubuntu-upstart:12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-14.04
  run_list:
  - "recipe[apt]"
  driver:
    image: ubuntu-upstart:14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  run_list:
  - "recipe[apt]"
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-7
  run_list:
  - "recipe[apt]"
  driver:
    image: debian:7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install lsb-release procps -y

# - name: centos-7.4
#   run_list:
#   - "recipe[yum]"
#   - "recipe[yum-epel]"

- name: centos-6
  run_list:
  - "recipe[yum]"
  - "recipe[yum-epel]"
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts

suites:
- name: default
  run_list:
  - "recipe[mongodb]"

- name: default_mongodb_org_repo
  run_list:
  - "recipe[mongodb]"
  attributes:
    mongodb:
      install_method: mongodb-org

- name: replicaset
  run_list:
  - "recipe[mongodb::replicaset]"
  attributes:
    mongodb:
      cluster_name: kitchen
      config:
        replSet: kitchen

- name: configserver
  run_list:
  - "recipe[mongodb::configserver]"

- name: mongos
  run_list:
  - "recipe[mongodb::mongos]"
  attributes:
    mongodb:
      cluster_name: default
      config:
        configdb: my_configserver

- name: mms_monitoring_agent
  run_list:
  - "recipe[mongodb::mms_monitoring_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        monitoring:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart is not present
    - debian-7.2.0

- name: mms_backup_agent
  run_list:
  - "recipe[mongodb::mms_backup_agent]"
  attributes:
    mongodb:
      mms_agent:
        api_key: "random key"
        backup:
          sslRequireValidServerCertificates: false
  excludes:
    # Upstart is not present
    - debian-7.2.0

- name: user_management
  run_list:
  - "recipe[mongodb::default]"
  - "recipe[mongodb::user_management]"
  attributes:
    mongodb:
      install_method: mongodb-org
      # Needed to read the correct config file
      # since mongo 2.6
      default_init_name: mongod
      dbconfig_file: mongodb.conf
      config:
        auth: true
